apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: busybox-error
  name: busybox-error
spec:
  containers:
  - args:
    - /bin/sh
    - -c
    - ls /notexist
    image: busybox
    name: busybox-error
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
