apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx-lp
  name: nginx-lp
spec:
  containers:
  - image: nginx
    name: nginx-lp
    livenessProbe:
      initialDelaySeconds: 5
      periodSeconds: 5
      exec:
        command:
        - ls
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
