apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx-http
  name: nginx-http
spec:
  containers:
  - image: nginx
    name: nginx-http
    readinessProbe:
      httpGet:
        path: "/"
        port: 80
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
