apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: nginx
  name: nginx
spec:
  ports:
  - port: 6262
    protocol: TCP
    targetPort: 6262
  selector:
    app: nginx
status:
  loadBalancer: {}
