apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2022-12-13T02:18:47Z"
  labels:
    app: nginx
  name: nginx
  namespace: default
spec:
  clusterIP: 10.101.118.86
  clusterIPs:
  - 10.101.118.86
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 
  selector:
    app: nginx
  sessionAffinity: None
  type: NodePort
