apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx-env
  name: nginx-env
spec:
  containers:
  - env:
    - name: var1
      value: val1
    image: nginx
    name: nginx-env
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
