apiVersion: apps/v1
kind: ReplicaSet
metadata:
  annotations:
    deployment.kubernetes.io/desired-replicas: "2"
    deployment.kubernetes.io/max-replicas: "3"
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2022-12-10T03:21:53Z"
  generation: 1
  labels:
    app: nginx
    pod-template-hash: 578b7694b4
  name: nginx-578b7694b4
  namespace: default
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: Deployment
    name: nginx
    uid: cdf3d236-4ad9-4cad-b274-08fb4e1f0071
  resourceVersion: "31514"
  uid: 523c044c-939c-4d24-888e-822748ed4a8e
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
      pod-template-hash: 578b7694b4
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx
        pod-template-hash: 578b7694b4
    spec:
      containers:
      - image: nginx:1.18.0
        imagePullPolicy: IfNotPresent
        name: nginx
        ports:
        - containerPort: 80
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 2
  fullyLabeledReplicas: 2
  observedGeneration: 1
  readyReplicas: 2
  replicas: 2
